//var string = "Qu. 16. When a Man in the dark presses either corner of his Eye with his Finger, and turns his Eye away from his Finger, he will see a Circle of Colours like those in the Feather of a Peacock's Tail. If the Eye and the Finger remain quiet these Colours vanish in a second Minute of Time, but if the Finger be moved with a quavering Motion they appear again. Do not these Colours arise from such Motions excited in the bottom of the Eye by the Pressure and Motion of the Finger, as, at other times are excited there by Light for causing Vision? And do not the Motions once excited continue about a Second of Time before they cease? And when a Man by a stroke upon his Eye sees a flash of Light, are not the like Motions excited in the Retina by the stroke? And when a Coal of Fire moved nimbly in the circumference of a Circle, makes the whole circumference appear like a Circle of Fire; is it not because the Motions excited in the bottom of the Eye by the Rays of Light are of a lasting nature, and continue till the Coal of Fire in going round returns to its former place? And considering the lastingness of the Motions excited in the bottom of the Eye by Light, are they not of a vibrating nature? Qu. 19. Doth not the Refraction of Light proceed from the different density of this athereal Medium in different places, the Light receding always from the denser parts of the Medium? And is not the density thereof greater in free and open Spaces void of Air and other grosser Bodies, than within the Pores of Water, Glass, Crystal, Gems, and other compact Bodies? For when Light passes through Glass or Crystal, and falling very obliquely upon the farther Surface thereof is totally reflected, the total Reflexion ought to proceed rather from the density and vigour of the Medium without and beyond the Glass, than from the rarity and weakness thereof.";
var words = [
  "Qu.",
  "16.",
  "When",
  "a",
  "Man",
  "in",
  "the",
  "dark",
  "presses",
  "either",
  "corner",
  "of",
  "his",
  "Eye",
  "with",
  "his",
  "Finger,",
  "and",
  "turns",
  "his",
  "Eye",
  "away",
  "from",
  "his",
  "Finger,",
  "he",
  "will",
  "see",
  "a",
  "Circle",
  "of",
  "Colours",
  "like",
  "those",
  "in",
  "the",
  "Feather",
  "of",
  "a",
  "Peacock's",
  "Tail.",
  "If",
  "the",
  "Eye",
  "and",
  "the",
  "Finger",
  "remain",
  "quiet",
  "these",
  "Colours",
  "vanish",
  "in",
  "a",
  "second",
  "Minute",
  "of",
  "Time,",
  "but",
  "if",
  "the",
  "Finger",
  "be",
  "moved",
  "with",
  "a",
  "quavering",
  "Motion",
  "they",
  "appear",
  "again.",
  "Do",
  "not",
  "these",
  "Colours",
  "arise",
  "from",
  "such",
  "Motions",
  "excited",
  "in",
  "the",
  "bottom",
  "of",
  "the",
  "Eye",
  "by",
  "the",
  "Pressure",
  "and",
  "Motion",
  "of",
  "the",
  "Finger,",
  "as,",
  "at",
  "other",
  "times",
  "are",
  "excited",
  "there",
  "by",
  "Light",
  "for",
  "causing",
  "Vision?",
  "And",
  "do",
  "not",
  "the",
  "Motions",
  "once",
  "excited",
  "continue",
  "about",
  "a",
  "Second",
  "of",
  "Time",
  "before",
  "they",
  "cease?",
  "And",
  "when",
  "a",
  "Man",
  "by",
  "a",
  "stroke",
  "upon",
  "his",
  "Eye",
  "sees",
  "a",
  "flash",
  "of",
  "Light,",
  "are",
  "not",
  "the",
  "like",
  "Motions",
  "excited",
  "in",
  "the",
  "Retina",
  "by",
  "the",
  "stroke?",
  "And",
  "when",
  "a",
  "Coal",
  "of",
  "Fire",
  "moved",
  "nimbly",
  "in",
  "the",
  "circumference",
  "of",
  "a",
  "Circle,",
  "makes",
  "the",
  "whole",
  "circumference",
  "appear",
  "like",
  "a",
  "Circle",
  "of",
  "Fire;",
  "is",
  "it",
  "not",
  "because",
  "the",
  "Motions",
  "excited",
  "in",
  "the",
  "bottom",
  "of",
  "the",
  "Eye",
  "by",
  "the",
  "Rays",
  "of",
  "Light",
  "are",
  "of",
  "a",
  "lasting",
  "nature,",
  "and",
  "continue",
  "till",
  "the",
  "Coal",
  "of",
  "Fire",
  "in",
  "going",
  "round",
  "returns",
  "to",
  "its",
  "former",
  "place?",
  "And",
  "considering",
  "the",
  "lastingness",
  "of",
  "the",
  "Motions",
  "excited",
  "in",
  "the",
  "bottom",
  "of",
  "the",
  "Eye",
  "by",
  "Light,",
  "are",
  "they",
  "not",
  "of",
  "a",
  "vibrating",
  "nature?",
  "Qu.",
  "19.",
  "Doth",
  "not",
  "the",
  "Refraction",
  "of",
  "Light",
  "proceed",
  "from",
  "the",
  "different",
  "density",
  "of",
  "this",
  "athereal",
  "Medium",
  "in",
  "different",
  "places,",
  "the",
  "Light",
  "receding",
  "always",
  "from",
  "the",
  "denser",
  "parts",
  "of",
  "the",
  "Medium?",
  "And",
  "is",
  "not",
  "the",
  "density",
  "thereof",
  "greater",
  "in",
  "free",
  "and",
  "open",
  "Spaces",
  "void",
  "of",
  "Air",
  "and",
  "other",
  "grosser",
  "Bodies,",
  "than",
  "within",
  "the",
  "Pores",
  "of",
  "Water,",
  "Glass,",
  "Crystal,",
  "Gems,",
  "and",
  "other",
  "compact",
  "Bodies?",
  "For",
  "when",
  "Light",
  "passes",
  "through",
  "Glass",
  "or",
  "Crystal,",
  "and",
  "falling",
  "very",
  "obliquely",
  "upon",
  "the",
  "farther",
  "Surface",
  "thereof",
  "is",
  "totally",
  "reflected,",
  "the",
  "total",
  "Reflexion",
  "ought",
  "to",
  "proceed",
  "rather",
  "from",
  "the",
  "density",
  "and",
  "vigour",
  "of",
  "the",
  "Medium",
  "without",
  "and",
  "beyond",
  "the",
  "Glass,",
  "than",
  "from",
  "the",
  "rarity",
  "and",
  "weakness",
  "thereof."
]

/*
for (var i = 0; i < words.length; i++){
  if (dict[words[i]]== undefined){
    dict[words[i]]= 1;
  }
  else{
    dict[words[i]]+= 1;
  }
};
*/

var dict =  {
  "Qu.": 2,
  "16.": 1,
  "When": 1,
  "a": 14,
  "Man": 2,
  "in": 11,
  "the": 37,
  "dark": 1,
  "presses": 1,
  "either": 1,
  "corner": 1,
  "of": 24,
  "his": 5,
  "Eye": 7,
  "with": 2,
  "Finger,": 3,
  "and": 11,
  "turns": 1,
  "away": 1,
  "from": 6,
  "he": 1,
  "will": 1,
  "see": 1,
  "Circle": 2,
  "Colours": 3,
  "like": 3,
  "those": 1,
  "Feather": 1,
  "Peacock's": 1,
  "Tail.": 1,
  "If": 1,
  "Finger": 2,
  "remain": 1,
  "quiet": 1,
  "these": 2,
  "vanish": 1,
  "second": 1,
  "Minute": 1,
  "Time,": 1,
  "but": 1,
  "if": 1,
  "be": 1,
  "moved": 2,
  "quavering": 1,
  "Motion": 2,
  "they": 3,
  "appear": 2,
  "again.": 1,
  "Do": 1,
  "not": 7,
  "arise": 1,
  "such": 1,
  "Motions": 5,
  "excited": 6,
  "bottom": 3,
  "by": 6,
  "Pressure": 1,
  "as,": 1,
  "at": 1,
  "other": 3,
  "times": 1,
  "are": 4,
  "there": 1,
  "Light": 5,
  "for": 1,
  "causing": 1,
  "Vision?": 1,
  "And": 5,
  "do": 1,
  "once": 1,
  "continue": 2,
  "about": 1,
  "Second": 1,
  "Time": 1,
  "before": 1,
  "cease?": 1,
  "when": 3,
  "stroke": 1,
  "upon": 2,
  "sees": 1,
  "flash": 1,
  "Light,": 2,
  "Retina": 1,
  "stroke?": 1,
  "Coal": 2,
  "Fire": 2,
  "nimbly": 1,
  "circumference": 2,
  "Circle,": 1,
  "makes": 1,
  "whole": 1,
  "Fire;": 1,
  "is": 3,
  "it": 1,
  "because": 1,
  "Rays": 1,
  "lasting": 1,
  "nature,": 1,
  "till": 1,
  "going": 1,
  "round": 1,
  "returns": 1,
  "to": 2,
  "its": 1,
  "former": 1,
  "place?": 1,
  "considering": 1,
  "lastingness": 1,
  "vibrating": 1,
  "nature?": 1,
  "19.": 1,
  "Doth": 1,
  "Refraction": 1,
  "proceed": 2,
  "different": 2,
  "density": 3,
  "this": 1,
  "athereal": 1,
  "Medium": 2,
  "places,": 1,
  "receding": 1,
  "always": 1,
  "denser": 1,
  "parts": 1,
  "Medium?": 1,
  "thereof": 2,
  "greater": 1,
  "free": 1,
  "open": 1,
  "Spaces": 1,
  "void": 1,
  "Air": 1,
  "grosser": 1,
  "Bodies,": 1,
  "than": 2,
  "within": 1,
  "Pores": 1,
  "Water,": 1,
  "Glass,": 2,
  "Crystal,": 2,
  "Gems,": 1,
  "compact": 1,
  "Bodies?": 1,
  "For": 1,
  "passes": 1,
  "through": 1,
  "Glass": 1,
  "or": 1,
  "falling": 1,
  "very": 1,
  "obliquely": 1,
  "farther": 1,
  "Surface": 1,
  "totally": 1,
  "reflected,": 1,
  "total": 1,
  "Reflexion": 1,
  "ought": 1,
  "rather": 1,
  "vigour": 1,
  "without": 1,
  "beyond": 1,
  "rarity": 1,
  "weakness": 1,
  "thereof.": 1
}

var screen = document.getElementById('#main');
for (var i = 0; i < words.length; i++){
  if (words[i]=="Qu.") {
    screen.innerHTML = screen.innerHTML + "<br>" + "</br>" + "<h3 class='fade normal'>" + "&nbsp" + "&nbsp" + "&nbsp" + "&nbsp" + words[i] + "</h3>";
    continue;
  }
  if (dict[words[i]]>3){
    screen.innerHTML = screen.innerHTML + "<h1 class='fade normal'>" + words[i] + "</h1>";
  }
  else if (dict[words[i]]<4 && dict[words[i]]>1) {
    screen.innerHTML = screen.innerHTML + "<h2 class='fade normal'>" + words[i] + "</h2>";
  }
  else{
    screen.innerHTML = screen.innerHTML + "<h3 class='fade normal'>" + words[i] + "</h3>";
  }
};
